services:
  jwt-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${JWT_PORT:-8080}:${JWT_PORT:-8080}"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:16.9-bullseye
    container_name: postgres-jwt
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-jwtdb}"]
      interval: 5s
      timeout: 5s
      retries: 5